export const lang = {
  "it": {
    "name": "Nome",
    "height" : "Altezza",
    "width" : "Larghezza",
    "background": "Background",
    "offsetX" : "Coordinata X",
    "offsetY" : "Coordinata Y",
    "custom-polygon" : "Personalizza forma",
    "bg-color": "Colore sfondo",
    "delete" : "Elimina",
    "always-on-top" : "Imposta lo schermo in sempre in primo piano",
    "polygonX" : "X del poligono",
    "polygonY" : "Y del poligono",
  },
  "en": {
    "name": "Name",
    "height" : "Height",
    "width" : "Width",
    "background": "Background",
    "offsetX" : "Coordinate X",
    "offsetY" : "Coordinate Y",
    "custom-polygon" : "Custom shape",
    "bg-color": "Bg color",
    "delete" : "Delete",
    "always-on-top" : "Set always on top",
    "polygonX" : "X del poligono",
    "polygonY" : "Y del poligono",
  }
};