export const lang = {
  "it": {
    "header": "Lista monitor",
    "monitor-to-add" :"Aggiungi un monitor alla configurazione",
    "name" : "Nome",
    "height" : "Altezza",
    "width" : "Larghezza",
    "offsetX" : "Coordinata X",
    "offsetY" : "Coordinata Y",
    "custom-polygon" : "Personalizza forma",
    "add" : "Aggiugi",
    "save" : "Salva",
    "update" : "Modifica",
    "father-monitor" : "Monitor padre",
    "search-file" : "Carica file",
    "tag" : 'Tag',
    "notify-save" : "Risorsa salvata",
    "notify-update" : "Risorsa modificata",
    "enable-multi-media": "Abilita multi media resource",
    "search-resource": "Cerca risorsa",
    "monitor": "Impianto"
  },
  "en": {
    "header": "List monitor",
    "monitor-to-add" :"Add a monitor to the configuration",
    "name" : "Name",
    "height" : "Height",
    "width" : "Width",
    "offsetX" : "Coordinate X",
    "offsetY" : "Coordinate Y",
    "custom-polygon" : "Custom shape",
    "add" : "Add",
    "save" : "Save",
    "update" : "Update",
    "father-monitor" : "Father monitor",
    "search-file" : "Load file",
    "tag" : 'Tag',
    "notify-save" : "Resource saved",
    "notify-update" : "Resource updated",
    "enable-multi-media": "Enable multi media resource",
    "search-resource": "Search resource",
    "monitor": "plant"
  }
};
