# Javascript Node CircleCI 2.0 configuration
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    resource_class: large
    docker:
      # specify the version you desire here
      - image: cimg/node:20.2.0

    working_directory: ~/repo

    steps:
      # Checkout project
      - checkout

      # Install wine32
      - run:
          name: Install wine32 to publish
          command: sudo apt-get update && sudo apt-get install wine32 rsync

      # Set Up Project
      - run:
          name: Npm install
          command: npm install

      # Install Snap (delete without snap)
      - run:
          name: Build polymer
          command: npm run polymer-build


      # Build sideline for all platform
      - run:
          name: Publish the release
          command: sudo npm run release


workflows:
  version: 2
  continuous-delivery-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
