export const lang = {
  "it": {
    "modify": "Modifica",
    "delete" : "Elimina",
    "play-resource" : "Play",
    "stop-resource" : "Stop",
    "pause-resource" : "Pausa",
    "rotation-no" : "Nessuna rotazione",
    "rotation-loop" : "Rotazione infinita",
    "rotation-infinity" : "Rotazione fissa",
    "overlay" : "Livello overlay",
    "standard" : "Livello standard",
    "idle": "fermo",
    "pause": "pausa",
    "running": "attivo",
    "size-normal": "dimentisione originale",
    "size-contain": "dimensione strecciata",
    "volume": "audio abilitato",
    "volume-off": "audio disabilitato",
  },
  "en": {
    "modify": "Modify",
    "delete" : "Delete",
    "play-resource" : "Play",
    "stop-resource" : "Stop",
    "pause-resource" : "Pause",
    "rotation-no" : "Nessuna rotazione",
    "rotation-loop" : "Rotazione infinita",
    "rotation-infinity" : "Rotazione fissa",
    "overlay" : "send-overlay",
    "standard" : "send-standard",
    "idle": "idle", 
    "pause": "pause",
    "running": "running",
    "size-normal": "normal fit",
    "size-contain": "twisted fit",
    "volume": "volume enable",
    "volume-off": "volume disable",
  }
};
