export const lang = {
  "it": {
    "header": "Lista media device",
    "name": "Nome",
    "enable-audio" : "Abilita l'audio",
    "info-working" : "lavora solo sulle risorse video",
    "hours": "Ora",
    "minutes": "Minuti",
    "seconds": "Secondi",
    "hours-end": "Ora di fine",
    "minutes-end": "Minuto di fine",
    "seconds-end": "Secondi di fine",
    "type": "Tipo di timeline",
    "timeslot": "Timeslot",
    "add-to-timeline": "Aggiungi alla timeline",
    "bind-timeline": "Associa una timeline",
    "autostart": "Autostart",
    "save": "Salva",
    "update": "Modifica",
    "notify-save" : "Timeline saved",
    "notify-update" : "Timeline updated"
  },
  "en": {
    "header": "List media device",
    "name" : "Name",
    "enable-audio" : "Enable audio",
    "info-working" : "working only on video resource",
    "hours": "Hours",
    "minutes": "Minutes",
    "seconds": "Seconds",
    "hours-end": "End hours",
    "minutes-end": "End minutes",
    "seconds-end": "End seconds",
    "type": "Type of timeline",
    "timeslot": "Timeslot",
    "add-to-timeline": "Add to timeline",
    "bind-timeline": "Bind a timeline",
    "autostart": "Autostart",
    "save": "Save",
    "update": "Update",
    "notify-save" : "Timeline salvato",
    "notify-update" : "Timeline aggiornato"
  }
};
